export const HANDLE_AUTH = "HANDLE_AUTH";

// ADMIN LOGIN
export const ADMIN_LOGIN_LOADING = "ADMIN_LOGIN_LOADING";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const CLEAR_DETAILS = "CLEAR_DETAILS";

// ORDERS PAGE
export const SET_ORDER_ITEM = "SET_ORDER_ITEM";

// STORES PAGE
export const SET_STORES_DATA = "SET_STORES_DATA";
export const INCREASE_PAGE_INDEX = "INCREASE_PAGE_INDEX";
export const DECREASE_PAGE_INDEX = "DECREASE_PAGE_INDEX";
export const SET_FILTER_NAME_VALUE = "SET_FILTER_NAME_VALUE";
