export const HANDLE_AUTH = 'HANDLE_AUTH';

// ADMIN LOGIN
export const ADMIN_LOGIN_LOADING = 'ADMIN_LOGIN_LOADING';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const CLEAR_DETAILS = 'CLEAR_DETAILS';
